apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        app: app
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: SPRING_DATASOURCE_PASSWORD
          value: root
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://db:3306/todoItem?characterEncoding=utf8
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        image: dhlpj/todolist-app:v1
        name: app
        ports:
        - containerPort: 8080
        resources: {}
        volumeMounts:
        - mountPath: /vol/development
          name: app-claim0
      restartPolicy: Always
      volumes:
      - name: app-claim0
        persistentVolumeClaim:
          claimName: app-claim0
status: {}
