apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        app: db
        io.kompose.service: db
    spec:
      containers:
      - args:
        - mysqld
        - --innodb-buffer-pool-size=20M
        - --character-set-server=utf8
        - --collation-server=utf8_general_ci
        - --default-time-zone=+8:00
        - --lower-case-table-names=1
        env:
        - name: MYSQL_DATABASE
          value: todoItem
        - name: MYSQL_ROOT_HOST
          value: '%'
        - name: MYSQL_ROOT_PASSWORD
          value: root
        image: mysql:5.5
        name: db
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
