apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        app: web
        io.kompose.service: web
    spec:
      containers:
      - args:
        - /bin/bash
        - -c
        - nginx -g 'daemon off;'
        image: dhlpj/todolist-web:v1
        name: web
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
